/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Byte Production Autobuyer": "字节生产自动购买者",
    "Bit Production Autobuyer": "比特生产自动购买者",
    "About": "关于",
    "Bits": "比特",
    "Blue": "蓝色",
    "Bytes": "字节",
    "Upgrades": "升级",
    "WARNING": "警告",
    "Water": "水",
    "Unlock computers?": "解锁计算机？",
    "Unlock files?": "解锁文件？",
    "Unlock servers?": "解锁服务器？",
    "Transferring resets all of your bits, bytes, upgrades, files, and computers, but you will gain words based on your bytes. You need to get 160 total computer levels to transfer.": "传输会重置您的所有比特、字节、升级、文件和计算机，但您将根据您的字节获得字数。 您需要获得 160 个总计算机级别才能传输。",
    "Transfer": "传输",
    "Total words injected": "注入的总字数",
    "Total words gained": "获得的总字数",
    "Total upgrades bought": "购买的升级总数",
    "Total SXP gained": "获得的总 SXP",
    "Total servers made": "制造的服务器总数",
    "Total server level ups": "服务器升级总数",
    "Total level ups": "总升级等级",
    "Total files dissolved": "解散文件总数",
    "Total EXP gained": "经验获得总数",
    "Total computer level ups": "计算机总升级",
    "Total bytes gained": "获得的总字节数",
    "Total bits injected": "注入的总比特数",
    "Total bits gained": "获得的总比特数",
    "Times transferred": "传输的次数",
    "Time since last transfer": "自上次传输以来的时间",
    "This game has been now archived after few years of development. I am not deleting this for historic purposes. You are feel free to still play this game, but however you will probably not enjoy it.": "经过几年的开发，这款游戏现已存档。 我不是出于历史目的删除它。 您可以继续玩这个游戏，但您可能不会喜欢它。",
    "Select the file you want to dissolve.": "选择您要解散的文件。",
    "Saving": "保存",
    "Red Beryl": "红绿柱石色",
    "Reload": "重载",
    "Red": "红色",
    "Quality of Life": "生活质量",
    "Purple": "紫色",
    "Productive Data": "生产数据",
    "Producing": "生产中",
    "Produce": "生产",
    "Playtime": "游戏时长",
    "Pink": "粉色",
    "Orange": "橙色",
    "Or are you want to perm-unlock files?": "或者您想永久解锁文件？",
    "Or are you want to perm-unlock computers?": "或者您想对计算机进行永久解锁？",
    "Options": "选项",
    "NG+3 Server": "NG+3服务器",
    "Max upgrades": "最大升级",
    "Lime": "酸橙色",
    "Jade": "玉石色",
    "Inject words": "注入文字",
    "Inject": "注入",
    "Inject all words evenly": "均匀注入所有单词",
    "Increase the byte production by 50%.": "将字节产量提高 50%。",
    "Increase the bit production by 50%.": "将比特产量提高 50%。",
    "Increase the bit capacity by 50%.": "将比特容量增加 50%。",
    "If you are seeing this sentence for few seconds, please reload or export your save!": "如果您看到这句话几秒钟，请重新加载或导出您的保存！",
    "Home": "家",
    "Aarex's Home": "Aarex 的家",
    "Computers": "计算机",
    "Cyan": "青色",
    "Display": "显示",
    "Dissolve": "溶解",
    "Dissolve for SXP": "溶解为 SXP",
    "Fastest transfer": "最快的传输",
    "Feats": "专长",
    "Files": "文件",
    "Green": "绿色",
    "Here is your exported save. You can share it for reporting bugs.": "这是您导出的存档。 您可以共享它以报告错误。",
    "#1: Transfer in under 10 seconds.": "#1：在 10 秒内传输。",
    "#2: Transfer with 1 server used.": "#2：使用 1 个服务器进行传输。",
    "Percentage of data to be injected": "要注入的数据百分比",
    "Total multiplier on bit and byte productions": "比特和字节生产的总乘数",
    "Yellow": "黄色",
    "Light": "灯光",
    "Dark": "暗色",
    "Normal": "正常",
    "Scientific": "科学计数法",
    "Engineering": "工程符号",
    "Letters": "字母",
    "Logarithm": "对数",
    "Standard": "标准",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Created by Aarex Tiaokhiao": "由 Aarex Tiaokhiao 创建",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "\t\t\t\t\t": "",
    "Currently: ": "当前: ",
    "Level: ": "等级: ",
    "Multiplier: ": "乘数: ",
    "Auto save: ": "自动保存: ",
    "Color: ": "颜色: ",
    "Dark: ": "深色: ",
    "Light: ": "灯光: ",
    "Locked bits production: ": "锁定比特生产: ",
    "Offline progress: ": "离线进度: ",
    "Notation: ": "符号: ",
    "Tick rate: ": "更新频率: ",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t\t\t": "\n\t\t\t\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^(.+) \/ (.+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^(\d+) day, (\d+) minutes, and (\d+) seconds$/, '$1天 $2分钟 $3秒'],
    [/^(\d+) day, (\d+) hours, (\d+) minutes, and (\d+) seconds$/, '$1天 $2小时 $3分钟 $4秒'],
    [/^(\d+) days, (\d+) hours, (\d+) minutes, and (\d+) seconds$/, '$1天 $2小时 $3分钟 $4秒'],
    [/^(\d+) day, (\d+) hour, (\d+) minutes, and (\d+) seconds$/, '$1天 $2小时 $3分钟 $4秒'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Upgrade (.+) Autobuyer$/, '升级 $1 自动购买者'],
    [/^File (.+) Autobuyer$/, '文件 $1 自动购买者'],
    [/^Computer (.+) Autobuyer$/, '计算机 $1 自动购买者'],
    [/^File \#(\d+)$/, '文件 \#$1'],
    [/^Cost: (.+) words$/, '成本: $1 字'],
    [/^Cost: (.+) bytes$/, '成本: $1 字节'],
    [/^([\d\.]+) bits$/, '$1 比特'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+)x multiplier$/, '$1x 乘数'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);